language: go

sudo: false

go:
    - 1.4
    - tip

before_install:
    - go get github.com/kr/godep
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/stretchr/testify
    - go get github.com/golang/lint/golint

install:
    - godep restore

script:
    - golint ./...
    - go test -race -cover -v ./...

matrix:
    allow_failures:
        - go: tip
